### ISSUE TITLE
Edit draft

### ISSUE THREAD

**Issue by ddanzer** [QuaCaTeam/quaca#70]
Please check the draft in the branch "paper_draft". Directly implement your modifications.

- [x] @SiMaHer 
- [x] @chegerland 
- [x] @myoelmy

**Comment by myoelmy** [comment]
In __Summary__ there is only one (the first) sentence about QuaCa. This might be an issue, since this paper is focusing on QuaCa. Maybe we can extend the description in a second sentence by something like: Due to its modular domain-driven structure QuaCa can be use to rapidly calculate further relevant quantities from this realm of physics.

Besides this, it sounds really good to me :+1:
